const path=require('path'),http=require('http'),express=require('express');const{Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server),PORT=process.env.PORT||3000,DT=1/60;
const ARENA={width:1000,floor:500,playerWidth:52,playerHeight:118},rooms=new Map();
app.use(express.static(path.join(__dirname,'public')));app.get('*splat',(_q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));
function roomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let c;do{c=Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}while(rooms.has(c));return c}
function teamOf(n){return n%2?'red':'blue'}
function spawnX(n,mode){return mode==='2v2'?[150,850,300,700][n-1]:[210,790][n-1]}
function fighter(id,n,mode){return{id,number:n,team:teamOf(n),x:spawnX(n,mode),y:382,vx:0,vy:0,hp:100,guard:100,facing:n%2?1:-1,grounded:true,attacking:false,attackAirborne:false,attackAt:0,lastAttack:0,hitDone:false,flashUntil:0,stunUntil:0,input:{left:false,right:false,guard:false,crouch:false}}}
function publicPlayer(p){return{id:p.id,number:p.number,team:p.team,x:+p.x.toFixed(1),y:+p.y.toFixed(1),hp:p.hp,guard:Math.round(p.guard),facing:p.facing,attacking:p.attacking,guarding:p.input.guard,crouching:p.input.crouch,stunned:Date.now()<p.stunUntil,hit:Date.now()<p.flashUntil}}
function emitState(r){io.to(r.code).emit('gameState',{phase:r.phase,countdown:r.countdown,mode:r.mode,capacity:r.capacity,players:[...r.players.values()].map(publicPlayer)})}
function reset(r){[...r.players.values()].sort((a,b)=>a.number-b.number).forEach((p,i)=>Object.assign(p,fighter(p.id,i+1,r.mode)));clearInterval(r.timer);r.timer=null;r.phase=r.players.size===r.capacity?'countdown':'waiting';r.countdown=r.phase==='countdown'?3:0;if(r.phase==='countdown'){io.to(r.code).emit('roundReset');io.to(r.code).emit('countdown',3);r.timer=setInterval(()=>{r.countdown--;if(r.countdown>0)io.to(r.code).emit('countdown',r.countdown);else{clearInterval(r.timer);r.timer=null;r.phase='fighting';io.to(r.code).emit('fight')}emitState(r)},1000)}emitState(r)}
function join(socket,r){const n=r.players.size+1;socket.join(r.code);socket.data.roomCode=r.code;r.players.set(socket.id,fighter(socket.id,n,r.mode));socket.emit('roomJoined',{roomCode:r.code,playerId:socket.id,playerNumber:n,team:teamOf(n),mode:r.mode,capacity:r.capacity,arena:ARENA});io.to(r.code).emit('playerCount',{count:r.players.size,capacity:r.capacity});if(r.players.size===r.capacity)reset(r);else emitState(r)}
function finish(r,winningTeam){if(r.phase!=='fighting')return;r.phase='finished';const winners=[...r.players.values()].filter(p=>p.team===winningTeam).map(p=>p.id);const losers=[...r.players.values()].filter(p=>p.team!==winningTeam).map(p=>p.id);io.to(r.code).emit('gameOver',{winningTeam,winnerIds:winners,loserIds:losers,winnerHp:[...r.players.values()].filter(p=>p.team===winningTeam).reduce((s,p)=>s+p.hp,0)});emitState(r)}
function reindex(r){[...r.players.values()].sort((a,b)=>a.number-b.number).forEach((p,i)=>Object.assign(p,fighter(p.id,i+1,r.mode)))}
io.on('connection',socket=>{
 function leave(){const r=rooms.get(socket.data.roomCode);if(!r)return;r.players.delete(socket.id);socket.leave(r.code);delete socket.data.roomCode;clearInterval(r.timer);r.timer=null;if(!r.players.size)return rooms.delete(r.code);reindex(r);r.phase='waiting';r.countdown=0;io.to(r.code).emit('opponentLeft');io.to(r.code).emit('playerCount',{count:r.players.size,capacity:r.capacity});emitState(r)}
 socket.on('createRoom',raw=>{if(socket.data.roomCode)return;const mode=raw==='2v2'?'2v2':'1v1',r={code:roomCode(),mode,capacity:mode==='2v2'?4:2,players:new Map(),phase:'waiting',countdown:0,timer:null};rooms.set(r.code,r);join(socket,r)});
 socket.on('joinRoom',raw=>{if(socket.data.roomCode)return;const r=rooms.get(String(raw||'').trim().toUpperCase());if(!r)return socket.emit('roomError','議댁옱?섏? ?딅뒗 諛?肄붾뱶?낅땲??');if(r.players.size>=r.capacity)return socket.emit('roomError','諛⑹씠 媛??李쇱뒿?덈떎.');join(socket,r)});
 socket.on('playerInput',v=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id);if(p){if('left'in(v||{}))p.input.left=!!v.left;if('right'in(v||{}))p.input.right=!!v.right;if('guard'in(v||{}))p.input.guard=!!v.guard;if('crouch'in(v||{}))p.input.crouch=!!v.crouch}});
 socket.on('jump',()=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id),now=Date.now();if(p&&p.hp>0&&r.phase==='fighting'&&p.grounded&&!p.input.guard&&!p.input.crouch&&now>=p.stunUntil){p.vy=-620;p.grounded=false}});
 socket.on('punch',()=>{const r=rooms.get(socket.data.roomCode),p=r?.players.get(socket.id),now=Date.now();if(p&&p.hp>0&&r.phase==='fighting'&&!p.attacking&&!p.input.guard&&!p.input.crouch&&now>=p.stunUntil&&now-p.lastAttack>=520){p.attacking=true;p.attackAirborne=!p.grounded;p.attackAt=now;p.lastAttack=now;p.hitDone=false}});
 socket.on('restartGame',()=>{const r=rooms.get(socket.data.roomCode);if(r?.players.size===r?.capacity&&r.phase==='finished')reset(r)});socket.on('leaveRoom',leave);socket.on('disconnect',leave);
});
setInterval(()=>{for(const r of rooms.values()){if(r.phase!=='fighting'){emitState(r);continue}const list=[...r.players.values()],now=Date.now();for(const p of list){if(p.hp<=0){p.attacking=false;p.input.left=p.input.right=p.input.guard=p.input.crouch=false;continue}if(!p.input.guard)p.guard=Math.min(100,p.guard+18*DT);const enemies=list.filter(x=>x.team!==p.team&&x.hp>0).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x)),target=enemies[0];if(!target)continue;p.facing=target.x>=p.x?1:-1;const locked=p.input.guard||p.input.crouch||now<p.stunUntil||p.attacking;p.vx=locked?0:(Number(p.input.right)-Number(p.input.left))*235;p.vy+=1500*DT;p.x=Math.max(27,Math.min(973,p.x+p.vx*DT));p.y+=p.vy*DT;if(p.y>=382){p.y=382;p.vy=0;p.grounded=true}if(p.attacking){const elapsed=now-p.attackAt;if(!p.hitDone&&elapsed>=100&&elapsed<=245){const dx=target.x-p.x,inFront=Math.sign(dx)===p.facing,inRange=Math.abs(dx)<=105&&Math.abs(target.y-p.y)<=(p.attackAirborne?150:78);if(inFront&&inRange){p.hitDone=true;const targetFacing=Math.sign(p.x-target.x)===target.facing,blocked=target.input.guard&&targetFacing&&now>=target.stunUntil,evaded=target.input.crouch&&target.grounded&&!p.attackAirborne;if(evaded){io.to(r.code).emit('attackResult',{type:'dodge',victimId:target.id})}else{const critical=p.attackAirborne&&!target.input.crouch,damage=blocked?2:critical?20:10;target.hp=Math.max(0,target.hp-damage);target.flashUntil=now+180;if(blocked){target.guard=Math.max(0,target.guard-25);if(target.guard===0){target.stunUntil=now+800;target.input.guard=false;io.to(r.code).emit('attackResult',{type:'guardBreak',victimId:target.id})}else io.to(r.code).emit('attackResult',{type:'block',victimId:target.id})}else{target.stunUntil=now+(critical?420:220);target.x=Math.max(27,Math.min(973,target.x+p.facing*(critical?50:25)));io.to(r.code).emit('attackResult',{type:critical?'critical':'hit',victimId:target.id,damage})}io.to(r.code).emit('hitLanded',{victimId:target.id,type:blocked?'block':critical?'critical':'hit'});if(!target.hp&&!list.some(x=>x.team===target.team&&x.hp>0))finish(r,p.team)}}}if(elapsed>=340)p.attacking=false}}
  for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j],gap=b.x-a.x;if(Math.abs(gap)<42){const fix=(42-Math.abs(gap))/2,sign=gap>=0?1:-1;a.x-=fix*sign;b.x+=fix*sign}}emitState(r)}},1000/60);
server.listen(PORT,'0.0.0.0',()=>console.log(`NEON CLASH running on ${PORT}`));

